### ISSUE TITLE
A question about the experimental results shown in Figure 3 in the paper.

### ISSUE THREAD

**Issue by J1anHui** [tsun/APA#1]
Hello, thank you for your work!

There's one thing I can't understand about your paper.
In the following figure, in the experimental results of mapping the intermediate perturbations at different layers to penultimate activation, **why did the accuracy of the red boxes decrease compared to the previous 1-3 layers?**

![image](https://github.com/tsun/APA/assets/150405074/0f956d0b-927d-466f-b7d1-4e48aec334f9)

Thank you again for your work, I am looking forward to your reply!

**Comment by tsun** [comment]
Hello, thanks for your question. To get the lower figure, we fixed the pertubation magnitude epsilon to be 10 for all four layers.  In the figure,  Layer 1 refers to output of first residual block, Layer 2 refers to second residual block, likewise for Layer 3,4. There are a few factors that may affect the performances of perturbing different layers.

- The output dimension (and feature norm) for each layer is quite different, therefore epsilon=10 may not be the optimal parameter for one specific layer.
- Layer 4 is connected to the bottleneck layer, different from Layer 1-3.

In the lower figure, we are not meant to compare across different layers. The decreased accuracy of Layer 4 is interesting. It may indicate that epsilon=10 is not a good parameter or perturbing this layer is not preferred.

**Comment by J1anHui** [comment]
Thank you so much for taking the time to answer my question.  Your help is greatly appreciated!
